### ISSUE TITLE
接口问题

### ISSUE THREAD

**Issue by 2314933036** [aimerforreimu/AUXPI#10]
能暴露下各个网站的上传接口以及data格式么?

**Comment by aimerforreimu** [comment]
请看`server`下面已经写的比较明确了
如果需要我可以抽空写一下

**Comment by 2314933036** [comment]
因为我学的是Python语言,所以还是希望可以提供下各大网站做接口的详细data格式,
我试过调用百度的那个接口,respons的内容说我意外的文件格式
接口http://image.baidu.com/pcdutu/a_upload?fr=html5&target=pcSearchImage&needJson=true
{'errno': -1, 'msg': {'code': 'LIMIT_UNEXPECTED_FILE', 'field': 'images', 'storageErrors': []}, 'type': 'img-upload'}
谢谢分享

**Comment by aimerforreimu** [comment]
有时间的话会写一下，但是这个东西还是最好自己研究下，分享出来被弄烂了大家都用不了
