### ISSUE TITLE
不能多图上传批量复制链接?

### ISSUE THREAD

**Issue by weiyidu** [aimerforreimu/auxpi#11]

**Comment by aimerforreimu** [comment]
可以是可以，如果你是管理员可以在后台复制链接，不过貌似用户页面不行，感谢提醒，下个版本改进一下

**Comment by aimerforreimu** [comment]
可以是可以，如果你是管理员可以在后台复制链接，不过貌似用户页面不行，感谢提醒，下个版本改进一下

**Comment by weiyidu** [comment]
> 可以是可以，如果你是管理员可以在后台复制链接，不过貌似用户页面不行，感谢提醒，下个版本改进一下

如果有个交流群会更好，
我看到V2会返回所有链接，这样是不是做到图片外链从统一的域名出去，然后轮询上传的图床，假如第一个图床失效，程序自动去找第二个，这样基本可以保障图片外链不会失效。

**Comment by aimerforreimu** [comment]
不是轮询，是直接异步并发上传，毕竟是Go程序，不用点并发特性就没特色了嘛

**Comment by weiyidu** [comment]
> 不是轮询，是直接异步并发上传，毕竟是Go程序，不用点并发特性就没特色了嘛

可能是我的表述有点问题。
比如把图片1.jgp同时上传到百度、新浪、搜狗，得到的三个外链。
现在我用百度的外链，假如一天百度的外链失效了；新浪和搜狗的外链还可以使用。
图片少了可以手动操作，时久了或者图片多的时候就很难了。
程序能不能做到百度失效之后，自动去找新浪或者搜狗？
之前见过类似的程序，现在找不到了。

**Comment by aimerforreimu** [comment]
这个倒是没问题，可以考虑加入，但是失效检测这个东西如果图片多了的话，可能不能保持随时检测

**Comment by weiyidu** [comment]
> 这个倒是没问题，可以考虑加入，但是失效检测这个东西如果图片多了的话，可能不能保持随时检测

可以在管理后台添加个定时检测任务功能

**Comment by aimerforreimu** [comment]
图片多了智能定时检测，而且如果图片超过一定数量可能要舍弃一部分检测

**Comment by weiyidu** [comment]
> 图片多了只能定时检测，而且如果图片超过一定数量可能要舍弃一部分图片的检测

很期待这个功能上线，以后做图站就爽歪歪了。

**Comment by SayaBear** [comment]
UP，同样期待这个新功能

**Comment by HaoweiCh** [comment]
好东西，框架我很感兴趣，谢谢分享

**Comment by lirko** [comment]
搜狗好像已经失效了,有时间限制,一过时间就 404..

功能很喜欢,但环境可能有点麻烦, 一个正常的 web 环境 linux 宝塔安装了 nginx php mysql 等环境不敢乱上这个源码的脚本搭环境,生怕 web 环境受到影响...

给个建议:
上传或 api 图片,服务器以 MD5 名称先保存到服务器本地备份,图片 MD5 记录到 mysql 里返回标准 url
http://test/MD5
后台选择本地,sina,smms 等任意一个返回图片地址
mysql 字段用 id,MD5,sinaurl,smmsurl,x1url,x2url,x3url 等等

流程:
图片上传服务器 - 服务器分发各大 api 平台 - 记录各大平台返回的图片地址到 mysql

后台指定开启本地图片或 sina 图床 - 访问 http://test/MD5 - 跳转本地或 sina 图片 url 

好处:各大平台有备份,url 也都保存 mysql 了,唯一标识就是 MD5 码

只要你写文章时调用的是 http://test/MD5,不管你正在使用的是什么图床平台,一旦平台挂了直接选择其他平台 url,假如全部平台挂了还有最安全的本地图片来调用..

就是说图片平台挂,不影响你发布文章调用的图片 url,因为后台一换平台就又正常恢复了,,

试想一下如果不是 md5 方式保存 sql,你写文章时用的是 sina 平台的图片 url,就算你分发到各大平台,但 sina 平台挂了,你的文章不就要一个一个图片替换 url 吗? 这个工作量可是非常恐怖了,如果是采用 http://test/MD5 来中转,你就不用担心平台挂了要去文章里替换图片地址的问题....

**Comment by aimerforreimu** [comment]
已完成分发，下个版本放出
