### ISSUE TITLE
利用图片中转url 随时切换各大图片平台

### ISSUE THREAD

**Issue by lirko** [aimerforreimu/auxpi#14]
搜狗好像已经失效了,有时间限制,一过时间就 404..

功能很喜欢,但环境可能有点麻烦, 一个正常的 web 环境 linux 宝塔安装了 nginx php mysql 等环境不敢乱上这个源码的脚本搭环境,生怕 web 环境受到影响...

给个建议:
上传或 api 图片,服务器以 MD5 名称先保存到服务器本地备份,图片 MD5 记录到 mysql 里返回标准 url
http://test/MD5
后台选择本地,sina,smms 等任意一个返回图片地址
mysql 字段用 id,MD5,sinaurl,smmsurl,x1url,x2url,x3url 等等

流程:
图片上传服务器 - 服务器分发各大 api 平台 - 记录各大平台返回的图片地址到 mysql

后台指定开启本地图片或 sina 图床 - 访问 http://test/MD5 - 跳转本地或 sina 图片 url 

好处:各大平台有备份,url 也都保存 mysql 了,唯一标识就是 MD5 码

只要你写文章时调用的是 http://test/MD5,不管你正在使用的是什么图床平台,一旦平台挂了直接选择其他平台 url,假如全部平台挂了还有最安全的本地图片来调用..

就是说图片平台挂,不影响你发布文章调用的图片 url,因为后台一换平台就又正常恢复了,,

试想一下如果不是 md5 方式保存 sql,你写文章时用的是 sina 平台的图片 url,就算你分发到各大平台,但 sina 平台挂了,你的文章不就要一个一个图片替换 url 吗? 这个工作量可是非常恐怖了,如果是采用 http://test/MD5 来中转,你就不用担心平台挂了要去文章里替换图片地址的问题....

**Comment by aimerforreimu** [comment]
宝塔就很简单了，有空写个教程
你这个想法我一直在考虑，感觉如果数据量大了可能会导致 mysql 的负载很大，但是可以用算法去解决这个问题，类似于新浪的短连接跳转。

可以加入下个版本的考虑范围

**Comment by lirko** [comment]
> 宝塔就很简单了，有空写个教程
> 你这个想法我一直在考虑，感觉如果数据量大了可能会导致mysql的负载很大，但是可以用算法去解决这个问题，类似于新浪的短连接跳转。
> 
> 可以加入下个版本的考虑范围

那选择可以加层redis就无敌了,,,毕竟单单存url数据1张图片顶多也就1kb,百万级别也就1g数据大小,问题是正常个人也不用了这么大级别,正常也就几十M数据量,何况目前基本都会搭建redis服务做缓存的

**Comment by aimerforreimu** [comment]
可以考虑，不过性能方面确实存在问题

**Comment by aimerforreimu** [comment]
完成分发，使用自动检测机制无需手动调参
