### ISSUE TITLE
作者大大，宝塔面板的教程有出了吗？

### ISSUE THREAD

**Issue by fanxiaole** [aimerforreimu/auxpi#19]
作者大大，宝塔面板的教程有出了吗？

**Comment by lirko** [comment]
同求,我按照网上教程搭建了bee等环境,再根据说明按照auxpi都无法正常使用,用的是centos宝塔

本地win7也试过搭建,还是无法成功... 

请作者出相关教程吧,,服务器分发会存在分发时占用大量流量带宽,
我更希望的是本地win7做分发,毕竟现在家庭带宽这么大,电脑硬盘容量也大...

要是本地上传图片到服务器,服务器又分发到各大平台,那基本服务器的带宽就被占用完了,什么都做不了

**Comment by aimerforreimu** [comment]
@lirko 分发并不是你所想的直接全部分发，而是按照权重去检测分发。auxpi的v2分发只会给你提供一个URL但是这个URL会302跳转到各种图床，当图片挂掉的时候自动检测机制触发，auxpi会自动从根节点取出图片上传到新的cdn上（看权重上传），然后更新数据库，重置缓存。最后实在没有地方可以上传了才会定向到本地或者其他根节点。目前支持3个根节点（本地算一个）

**Comment by aimerforreimu** [comment]
@fanxiaole 今天晚上出一下，最近有点忙

**Comment by aimerforreimu** [comment]
@lirko 另外不需要bee就可以运行auxpi，在win下面auxpi就是一个exe文件，从release中下载最新的win版，然后cmd/powershell输入start auxpi run，然后访问localhost:2333即可查看

以后可能会考虑向picgo一样独立内核然后写ui

**Comment by windxxcom** [comment]
@lirko 太厉害了，V2版本什么时间上线啊

**Comment by aimerforreimu** [comment]
@fanxiaole 宝塔安装教程已出

https://github.com/aimerforreimu/auxpi/wiki/%E4%BD%BF%E7%94%A8%E5%AE%9D%E5%A1%94%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85

**Comment by shyy06** [comment]
提示:
2019/10/17 11:08:34.448 [A] [main.go:43]  logs: duplicate adaptername "file" (you have set this logger before) 
2019/10/17 11:08:34.455 [I] [asm_amd64.s:1333]  http server Running on http://:2333
2019/10/17 11:08:34.455 [C] [asm_amd64.s:1333]  ListenAndServe:  listen tcp :2333: bind: address already in use


但是网站还是无法打开,直接访问域名提示403,访问域名+端口号无反应
