### ISSUE TITLE
搜狗图床后台无法解析，百度图床无法返回正常连接

### ISSUE THREAD

**Issue by zhucaidan** [aimerforreimu/auxpi#21]
大佬，目前遇到两个问题
1、如果使用搜狗图床上传的话，后台所有图片处无法解析
返回的链接是https://我的域名/api/proxy?url=https://img01.sogoucdn.com/app/a/图片连接
这种格式就导致了后台所有图片的搜狗图片无法解析，显示裂开图片
2、还有个是百度图床前台传完了以后，会显示连接为https://image.baidu.com/search/down?tn=download&url=
并不能正确的返回图片连接来复制
不知道是不是我安装问题还是程序问题，请帮忙看下，谢谢！

**Comment by aimerforreimu** [comment]
@zhucaidan 搜狗图床使用公共 CDN 可以进行反代，下个版本会修复的
很不幸百度图床这个 api 已经失效了，可能会被去除掉

**Comment by zhucaidan** [comment]
原来是这样啊
搜狗图床前台正常，就后台管理那里会显示不出来。。
还有个我发现新浪微博的图库不能传png会被自动转换成jpg，但是我去试了下新浪博客的可以，
但是博客的图库不让外链到别的网站，不知道有没有方式能解

**Comment by aimerforreimu** [comment]
你可以验证一下图片md5按理说是一样的

**Comment by zhucaidan** [comment]
期待大佬下个版本~

**Comment by lirko** [comment]
> 原来是这样啊
> 搜狗图床前台正常，就后台管理那里会显示不出来。。
> 还有个我发现新浪微博的图库不能传png会被自动转换成jpg，但是我去试了下新浪博客的可以，
> 但是博客的图库不让外链到别的网站，不知道有没有方式能解

新浪会压缩改变MD5的,至于png转jpg是因为新浪返回图片编码,,程序自己在返回的图片编码后面加.jpg而已,,其实你加不加后缀名都可以,你换.gif都可以

**Comment by ckz1211** [comment]
搜狗图床貌似不能外链？

**Comment by ckz1211** [comment]
> 
> 
> @zhucaidan 搜狗图床使用公共 CDN 可以进行反代，下个版本会修复的
> 很不幸百度图床这个 api 已经失效了，可能会被去除掉

搜狗图床貌似不能外链？
