### ISSUE TITLE
你好 ,如果使用Sharex 上传图片的话 怎么填写

### ISSUE THREAD

**Issue by deicol** [aimerforreimu/auxpi#23]
{
  "code": 10001,
  "msg": "上传文件为空",
  "data": null
}

image 类型如何填写 ?

![](https://wx2.sinaimg.cn/large/006GW5BMly1g1u2m8kg85j30eg0cx749.jpg)

**Comment by aimerforreimu** [comment]
image就需要是你的文件了，是file类型

**Comment by deicol** [comment]
老大有没有上传 示例 ..
![](https://i.loli.net/2019/04/07/5ca9e52037eec.gif)

**Comment by aimerforreimu** [comment]
我没有用过sharex 抱歉，找时间可以看一下

**Comment by deicol** [comment]
没有抱歉一说,有空可以了解一下,挺好用的一款开源截图软件 


| |
deicol
|
|
deicol@163.com
|
签名由网易邮箱大师定制
在2019年4月8日 11:30，aimerforreimu<notifications@github.com> 写道：

我没有用过sharex 抱歉，找时间可以看一下

**Comment by aimerforreimu** [comment]
看了下文档，写了一个 sharex 的插件，下个版本放出
