### ISSUE TITLE
请支持图片url远程上传

### ISSUE THREAD

**Issue by lirko** [aimerforreimu/auxpi#24]
很多时候并不是都必须使用post给api接口上传,能简化流程当然更简化!!

 比如我在网上看到一张配图
正常操作一: 保存电脑,打开图床程序选择图片提交上传
正常操作二:采集网页获取文章图片保存下载,写代码post图片到api接口,接收返回url,替换图片地址,发布..

以上是最常用的情景都存在的效率问题: 
保存下载- post到图床程序- 图床程序再post到平台接口, 
其中的(保存下载- post到图床程序) 这两步可以说完全多余的,如果直接post或get图片地址到图床程序能完成就增加很多流量时间效率

比如直接访问:http://test/get?http://sina.cn/img.jpg
图床服务器直接获取get?参数的图片地址进行保存下载,分发平台
返回图床程序的图片URL..

这样的流程就省下:
保存下载再上传图床程序
或
采集文章保存图片时要下载后post到图床程序的步骤..

**Comment by aimerforreimu** [comment]
为了安全考虑，url 暂不考虑，因为需要验证的东西太多了

**Comment by lirko** [comment]
> 为了安全，url 暂不考虑，因为需要验证的东西太多了

post api 方式不是也要附带AK验证吗?? 这个http://test/get?http://sina.cn/img.jpg&AK=XXXX不行吗

**Comment by aimerforreimu** [comment]
你考虑的太简单了url源是什么难道不需要检验？大小不需要限制？如果访问不了超时如何处理？

**Comment by lirko** [comment]
> 你考虑的太简单了url源是什么难道不需要检验？大小不需要限制？如果访问不了超时如何处理？

好吧..昨天意外发现一个网站 https://www.superbed.cn/ 他首页直接监控剪贴板图片url,自动上传..

网站分发3个平台,同时保存在服务器备份,,也是通过中转地址来检测平台是否正常,
