### ISSUE TITLE
大写扩展名无法上传

### ISSUE THREAD

**Issue by liumingye** [aimerforreimu/auxpi#28]
大写扩展名无法上传 提示文件类型错误

**Comment by aimerforreimu** [comment]
请出示logo

**Comment by aimerforreimu** [comment]
找到原因，下个版本修复

**Comment by liumingye** [comment]
![批注 2019-04-14 173302.png](https://test.demo-1s.com/images/2019/04/14/tKFwIUXH4lpPwQhI.)
![AuXpi 图床.png](https://test.demo-1s.com/images/2019/04/14/Xgd1nRJWy08UxdlN.)

**Comment by aimerforreimu** [comment]
fix
