### ISSUE TITLE
新浪图床已挂，站内图片无法访问

### ISSUE THREAD

**Issue by grandmasters** [aimerforreimu/auxpi#30]

**Comment by aimerforreimu** [comment]
已经找到解决方法，是否开源正在考虑，开源会导致这个方法失效，可能我会采取其他的方法解决这个问题

**Comment by ckz1211** [comment]
> 
> 
> 已经找到解决方法，是否开源正在考虑，开源会导致这个方法失效，可能我会采取其他的方法解决这个问题

https://test.demo-1s.com/
求测试网站的账号

**Comment by aimerforreimu** [comment]
@ckz1211
由于被人滥用暂时不开放了，等待下次大版本更新再开放

**Comment by ckz1211** [comment]
> 
> 
> @ckz1211
> 由于被人滥用暂时不开放了，等待下次大版本更新再开放

大佬有QQ么？想私信求个账号

**Comment by sukeycz** [comment]
1250499438

ckz1211 <notifications@github.com> 于2019年5月1日周三 下午9:40写道：

**Comment by sukeycz** [comment]
> > @ckz1211
> > 由于被人滥用暂时不开放了，等待下次大版本更新再开放
> 
> 大佬有QQ么？想私信求个账号

img.zxu.me

**Comment by jimisun123** [comment]
脚本安装已经30分钟+  撤了撤了
