### ISSUE TITLE
创建数据表出错

### ISSUE THREAD

**Issue by 5sir** [aimerforreimu/auxpi#32]
输入创建数据表命令后出现以下内容
https://img01.sogoucdn.com/app/a/100520146/96c98ef7f619fca94b43c4b6e329a43d

**Comment by aimerforreimu** [comment]
请说一下服务器环境，并且将模式改为 dev 在进行调试

**Comment by 5sir** [comment]
Centos7.5  PHP5.6+  MySQL 5.5.62  模式已为dev
上面图床好像挂了
https://ws2.sinaimg.cn/large/006Xmmmgly1g2l1mlnx60j30ux0b8my1.jpg

**Comment by aimerforreimu** [comment]
请使用一键脚本进行安装，您的这个问题可能是由于手动安装安装了老版本的 auxpi 导致的
