### ISSUE TITLE
本地图床上传无法返回正常值，且图片无法正常打开

### ISSUE THREAD

**Issue by saodaye** [aimerforreimu/auxpi#34]
https://ae01.alicdn.com/kf/UTB8WocrsL2JXKJkSanr7613lVXa7.png

也是头疼了。。。

配置：

BT，Nginx 1.15.9，PHP-5.6，phpMyAdmin 4.7

**Comment by saodaye** [comment]
- -昨天都还好好的，今天就不行了。昨天可以正常上传。

**Comment by aimerforreimu** [comment]
请见 [issue#35](https://github.com/aimerforreimu/auxpi/issues/35)
下个版本解决
