### ISSUE TITLE
本地图床上传文件不能带中文吗？

### ISSUE THREAD

**Issue by linxiwind** [aimerforreimu/auxpi#35]
本地图床上传文件不能带中文吗？同一个文件，文件名带中文字符生成的url就是错的。无中文字符就可以打开
如图
https://upload.torfirefox.name/images/2019/04/29/Ezt12ac7XeqZ0QSD.jpg

**Comment by aimerforreimu** [comment]
感谢反馈，大概知道问题了 
go 在使用 rune 处理中文编码的时候占用的内存和处理英文不一样，导致截取失败
下个版本将放弃 rune 处理后缀，使用 go 再带的 strings 包
