### ISSUE TITLE
创建数据表这一步出错 ./auxpi migrate

### ISSUE THREAD

**Issue by tt2014** [aimerforreimu/auxpi#36]
环境用的宝塔，centos7.6 php7.2 MySQL 5.6
具体：
[root@cc ~]# cd auxpi
[root@cc auxpi]# ./auxpi migrate
`` is not officially supported, running under compatibility mode.
2019/05/01 20:49:10 &{<nil> <nil> 0 <nil> false 0 {0xc0001be3c0} <nil> {{0 0} {<nil>} map[] 0} 0xc0000b4d10 0xfadfe0 0xc0001cda20 false}
2019/05/01 20:49:10 sql: unknown driver "" (forgotten import?)
2019/05/01 20:49:10 [info] replacing callback gorm:update_time_stamp from /Users/aimer/go/src/auxpi/models/models.go:69
2019/05/01 20:49:10 [info] replacing callback gorm:update_time_stamp from /Users/aimer/go/src/auxpi/models/models.go:70
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8908a6]

goroutine 1 [running]:
database/sql.(*DB).SetMaxIdleConns(0x0, 0xa)

/usr/local/Cellar/go/1.11/libexec/src/database/sql/sql.go:814 +0x26
auxpi/models.init.0()

/Users/aimer/go/src/auxpi/models/models.go:73 +0x72b
[root@cc auxpi]#

严格按照你的宝塔搭建教程来的，走到这一步就这样了，不知道啥原因，大佬帮看下

**Comment by aimerforreimu** [comment]
可否保留一下现场让我上去看一下，我本地没有遇到过这个状况

**Comment by tt2014** [comment]
没问题，要这么给你登录信息？
 
 
------------------ Original ------------------
From: "aimerforreimu"; 
Date: 2019年5月1日(星期三) 晚上10:44
To: "aimerforreimu/auxpi"; 
Cc: "Tian"<201821242074@scuec.edu.cn>; "Author"; 
Subject: Re: [aimerforreimu/auxpi] 创建数据表这一步出错 ./auxpi migrate (#36)

 

可否保留一下现场让我上去看一下，我本地没有遇到过这个状况

**Comment by tt2014** [comment]
> 可否保留一下现场让我上去看一下，我本地没有遇到过这个状况
> 如果方便，您可以把您的服务器登录信息发到我的邮箱中
> [aimerforreimu@gmail.com](mailto:aimerforreimu@gmail.com)

登录信息已发送到邮箱

**Comment by aimerforreimu** [comment]
问题解决了，你安装的不知道是哪个版本……
我刚才用一键安装脚本试了一下没问题的
