### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by LimeZky** [aimerforreimu/auxpi#37]
1，文档中的 手动安装 教程已经不能跟上时代了，如：路径不正确（原先的目录为：auxpi，现目录为auxpi/build/linux，请及时进行更新
2，项目中，用户头像无法正常加载，在用户中心中，用户上传的图片的缩略图无法加载，管理面板中也是如此，环境为宝塔，反代、Nginx配置已按照教程检查无误
3，网站Logo似乎不能使用ico格式？
4，API使用中的第一个参数（表单名称）是什么意思？我似乎不能理解

**Comment by aimerforreimu** [comment]
1.感谢建议，手动安装我会去掉的
2.头像用的新浪图床，所以会加载失败，在新的版本中新浪图床防盗链的问题我会给出解决方案
3.这个 logo 具体是指哪个 logo 呢？
4.第一个参数的类型是文件（即你要上传的图片的文件本体），字段名称是`image`

**Comment by LimeZky** [comment]
3、指的是Login页面的logo
4、emmm，那么我是直接丢个文件名上去还是base64之类的？
5，项目的管理面板中，本地储存的教程按钮点了没反应
6，任何图片的缩略图都无法加载

**Comment by aimerforreimu** [comment]
推荐安装最新版
