### ISSUE TITLE
关于新浪图床开启防盗链不显示的问题

### ISSUE THREAD

**Issue by icbao** [aimerforreimu/auxpi#39]
新浪图床最近开启了防盗链，直接访问可以显示但是网站中引用就无法显示图片
经过测试后发现将ws3替换为tva1后即可正常使用
那么问题来了，数据库中的我换了
后面上传的图片怎么换啊大佬

**Comment by aimerforreimu** [comment]
最新版本已经将控制反转，新浪这个我会单独留一个前缀供选择

**Comment by lirko** [comment]
既然已经有动作了就放弃新浪图床吧,这已经是警告了,,总有一天还是会做限制,向其他图床走起吧
