### ISSUE TITLE
请求修正前端页面的一些问题

### ISSUE THREAD

**Issue by ckz1211** [aimerforreimu/AUXPI#4]
经过这3天来的测试，在nginx的服务器上，如果使用http（80端口）来上图床网站，那么一切正常，很少会出现什么问题。但是，如果使用的是https（443端口）的话，那么nginx服务器端很容易对一部分图片返回400 Bad Request的错误。这错误发生频率很高，但帮助文档里，nginx的配置文档只写了80端口（仅http服务）。希望作者大大能在帮助文档里添加一下对https的优化支持，毕竟现在https是大趋势。我测试https的结果是——目前对于单张图片上传，10M以上的大图会100%报错，10M以下的单图上传一般没事。如果是批量上传小图，则图片数量多时会有一部分报错，图片平均体积越大，报错比例越高，我怀疑也同样是在上传图片总体积超过10M后开始报错……报错后需要重新上传，但重传时也可能再次报错……有时需要重传好几次才能全部传好，很麻烦……

**Comment by ckz1211** [comment]
查了下，貌似是搜狗(2M)、新浪(10M)，图片张数没限制？

**Comment by aimerforreimu** [comment]
1.能否提供具体的 Nginx 错误日志
2.10MB 已经不适合用 http 协议进行传输了，如果需要传输大文件，请等待我的另外一个项目

**Comment by ckz1211** [comment]
Nginx 错误日志里没有记录。主要错误集中在https传输，出现频率较大，10M以上大文件是100%出现，小文件批量传输时则是数量多时会有大部分出现错误，http传输时问题很少
https传输出错时，前端页面返回的错误提示就是nginx 400 Bad Request（没别的了）
http偶尔也会有错误，前端页面返回的错误提示是502 Bad Gateway（出现频率很低）

**Comment by aimerforreimu** [comment]
@ckz1211 
请把你的 Nginx 的站点配置贴出来
另外请更新最新的程序

**Comment by ckz1211** [comment]
``user  www www;
worker_processes auto;
error_log  /www/wwwlogs/nginx_error.log  crit;
pid        /www/server/nginx/logs/nginx.pid;
worker_rlimit_nofile 51200;

events
    {
        use epoll;
        worker_connections 65535;
        multi_accept on;
    }

http
    {
        include       mime.types;
		#include luawaf.conf;

		include proxy.conf;

        default_type  application/octet-stream;

        server_names_hash_bucket_size 512;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 256k;
        client_max_body_size 50m;

        sendfile   on;
        tcp_nopush on;

        keepalive_timeout 300;

        tcp_nodelay on;

        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 64k;
        fastcgi_buffers 4 64k;
        fastcgi_busy_buffers_size 128k;
        fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;

        gzip on;
        gzip_min_length 1k;
        gzip_buffers     4 16k;
        gzip_http_version 1.1;
        gzip_comp_level 5;
        gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml;
        gzip_vary on;
        gzip_proxied   expired no-cache no-store private auth;
        gzip_disable   "MSIE [1-6]\.";

        limit_conn_zone $binary_remote_addr zone=perip:10m;
		limit_conn_zone $server_name zone=perserver:10m;

        server_tokens off;
        access_log off;

server
    {
        listen 888;
        server_name www.bt.cn;
        index index.html index.htm index.php;
        root  /www/server/phpmyadmin;

        #error_page   404   /404.html;
        include enable-php.conf;

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log  /www/wwwlogs/access.log;
    }
include /www/server/panel/vhost/nginx/*.conf;
}

**Comment by ckz1211** [comment]
修正下，http模式也可能出错，代码是
007.jpg: Gateway Time-out
504 Gateway Time-out
nginx
![default](https://user-images.githubusercontent.com/5770954/51468996-322e0280-1dab-11e9-896d-da368532612e.png)

**Comment by aimerforreimu** [comment]
@ckz1211 
你这个不是站点配置吧，如果是的话你这个也没有进行反代呀，如果你用的是宝塔，就去看一下新的安装说明吧，里面有 https 的配置，注意是站点配置

[https 配置](https://github.com/aimerforreimu/AUXPI/wiki/%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2#3%E7%BB%91%E5%AE%9A%E5%9F%9F%E5%90%8D)

**Comment by ckz1211** [comment]
看了下站点配置的新版，和旧版的区别也就是去掉了缓存部分……
```
    location /
    {
        proxy_pass http://89.35.39.179:23333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        add_header X-Cache $upstream_cache_status;
        expires 12h;
    }
```

**Comment by ckz1211** [comment]
试了下新版，发现几个问题：
1、搜狗图床已经禁止外链了（这个和旧版的一样，旧版的也是这个月没法外链），希望能换下链接，找到搜狗外链的漏洞，没漏洞的话，搜狗只能弃了
2、部分图床缩图严重，稍后我详细测评下
3、新浪微博没开启原图上传（旧版我改了下代码，但新版一时半会没法改，因为那个nginx缓存老是妨碍我运行新版）
4、京东图床上传老是失败

**Comment by aimerforreimu** [comment]
@ckz1211 
说明一下你的几个问题的原因
1.关于 504 ，504状态码的出现大多数因为超时，因为你上传到图片太大，10MB 左右对于 http 协议来说已经有点大了可能会导致失败，请检查 nginx 允许上传文件的最大体积。另外你的上传带宽如果比较小，建议增大 nginx 的请求超时时间，否则就会出现 504 的问题，程序中我也会调整一下 server 的超时时间，让其可调
2.关于有损与无损:
其实新浪的都是会压缩的，如果需要无损，建议使用 Flickr 图床，不过这个图床需要申请账号，并且国内服务器传不上去
3.关于京东图床上传失败:
这次添加的图床中又很多一部分图床有大小和图片样式的限制，不是所有的图床都可以上传所有类型的图片，稍后会加在程序里

**Comment by ckz1211** [comment]
不，新浪图床真的可以上传无损jpg……
之前我拿了几张接近20M的超级大图（19M+)试了下，外链的都是无损原图，下载这些图片后，hash值计算和原图一样。当然，我都是http传的，https传10M以上的大图会100%报400错误
当然，超过20M的图会报错，这个是真没办法；png会被强制转jpg，所以也没法外链无损png

**Comment by ckz1211** [comment]
呃，我换了本地服务器，感觉好用多了，先关闭本主题了
