### ISSUE TITLE
360的图床问题

### ISSUE THREAD

**Issue by icbao** [aimerforreimu/auxpi#41]
发现360图床部分情况下获取链接失败直接把没有图片的开头链接存入了数据库
以及对大图压缩过度的问题https://ps.ssl.qhmsg.com/t017cc68c35e8d93a54.jpg
![image](https://user-images.githubusercontent.com/50193059/57117040-d00e7180-6d8b-11e9-8fe4-d3f6950687de.png)

**Comment by aimerforreimu** [comment]
新版本已经去掉 360，可能在未来会重新加上
