### ISSUE TITLE
用户管理问题

### ISSUE THREAD

**Issue by icbao** [aimerforreimu/auxpi#42]
用户注册后邮件并没有发送
确认了邮件配置正确
然后我关掉了邮箱
发现删除用户提示管理员无法删除管理员
明明是普通用户·-·
5.7的mysql

**Comment by aimerforreimu** [comment]
没听懂你在说什么

**Comment by icbao** [comment]
emmm怎么说呢
大致就是我用管理员删除普通用户提示管理员无法删除管理员

**Comment by aimerforreimu** [comment]
已经修复
