### ISSUE TITLE
图片显示问题以及新版本本地图床相关问题

### ISSUE THREAD

**Issue by icbao** [aimerforreimu/auxpi#45]
![image](https://user-images.githubusercontent.com/50193059/57172256-0f9e9180-6e50-11e9-92f4-3d92865d6bcb.png)
如上所见该图片并没有显示
另：新版的本地图床后台关闭后访问图床首页并不会暂不开放此图床。
而是正常的上传页面，但上传图片后提示返回参数错误
默认图床设置还是没法生效，进首页就是本地图床

**Comment by icbao** [comment]
BUG+1
![image](https://user-images.githubusercontent.com/50193059/57172593-cc92ed00-6e54-11e9-9738-e13442265622.png)
说明界面信息读取失败貌似，站点名称并不会替换
AuXpI API 图床
字样
![image](https://user-images.githubusercontent.com/50193059/57172608-f0eec980-6e54-11e9-914d-b67dc9bd4125.png)

**Comment by aimerforreimu** [comment]
建议使用最新版
