### ISSUE TITLE
默认图床问题

### ISSUE THREAD

**Issue by 66666666666666666666666** [aimerforreimu/auxpi#47]
本地图床已关闭 但首页默认图床仍然显示为本地图床且上传图片会提示上传参数错误  请问如何自定义默认图床为一个指定项呢？版本为V2.3.3

**Comment by aimerforreimu** [comment]
一直想弄个首页，奈何审美不好没有写，可能下个小版本会修改

**Comment by 66666666666666666666666** [comment]
好的 期待大佬更新
