### ISSUE TITLE
下载后执行安装脚本， 出现乱码

### ISSUE THREAD

**Issue by taraway** [aimerforreimu/auxpi#48]
下载成功了，手动运行 ./install.sh inetall
出现乱码，且安装并没有进行

![1](https://user-images.githubusercontent.com/3622406/57190590-4955c200-6f4e-11e9-9aa6-0c28a85f1bc7.png)

100%[===========================================>] 4,158       --.-K/s   in 0s

Last-modified header missing -- time-stamps turned off.
2019-05-05 15:52:25 (46.0 MB/s) - â€˜install.shâ€™ saved [4158/4158]
                          æ¬¡å®‰è£…

**Comment by aimerforreimu** [comment]
bash install. sh install

**Comment by taraway** [comment]
> bash install. sh install

![1](https://user-images.githubusercontent.com/3622406/57190651-43acac00-6f4f-11e9-9626-6310fb9299c2.png)

**Comment by taraway** [comment]
> bash install. sh install

是不是vps没装go环境 - -
