### ISSUE TITLE
前端部分的package包管理文件丢失

### ISSUE THREAD

**Issue by GanymedeNil** [aimerforreimu/auxpi#49]
## Bug report（问题描述）
.gitignore 屏蔽了所有的json文件导致前端的包版本管理文件丢失
#### Steps to reproduce（问题复现步骤）
无
#### Screenshot or Gif（截图或动态图）
无
#### Server environment（服务器环境）
- Your OS & version (服务器系统&版本):
windows 10
- DataBase & version (数据库&版本):
无
#### Other relevant information（格外信息）
- auxpi version:dev

**Comment by aimerforreimu** [comment]
fixed
