### ISSUE TITLE
修改此处设置，保存后不生效

### ISSUE THREAD

**Issue by taraway** [aimerforreimu/auxpi#50]
![1](https://user-images.githubusercontent.com/3622406/57214425-85575880-701c-11e9-9bf8-4eb2084c3c5e.png)

是否允许游客上传  这个选项

**Comment by aimerforreimu** [comment]
部分选项还在siteConfig.json当中，等待下次小版本更新或者手动改一次siteConfig.json的对应项

**Comment by aimerforreimu** [comment]
fixed
