### ISSUE TITLE
Windows版无法创建数据表

### ISSUE THREAD

**Issue by lirko** [aimerforreimu/auxpi#51]
![image](https://user-images.githubusercontent.com/18312470/57247408-58359500-7072-11e9-9d79-009c04b47660.png)

之前下载过win版本测试正常的,目前删除了数据库重新建了个空白库然后搭建最新版却创建数据表出错.,,,,唯独新版本出错是什么原因?

是不是忘记创建数据表步骤了?或者需要什么表字段我自己创建一下

**Comment by aimerforreimu** [comment]
请在app. conf中进行数据库的配置

**Comment by lirko** [comment]
> 请在app. conf中进行数据库的配置

已经设置过了,正常连接数据库,,只是创建数据表出错而已,,不是连接问题
