### ISSUE TITLE
cli 命令行上传 && 网页支持粘贴？

### ISSUE THREAD

**Issue by jinfagang** [aimerforreimu/auxpi#55]
不知道这两个功能是否可以支持，因为图床有时候得自己用，ubuntu下用cli比较方便，但是有时候只是截个图，没有必要把图片存储到本地，如果直接网页粘贴就比较完美了。

可以参考 imgchr.com 图创

**Comment by aimerforreimu** [comment]
感谢提议，下个版本加上粘贴上传cli可能要到下一个大版本

**Comment by jinfagang** [comment]
@aimerforreimu 期待ing
