### ISSUE TITLE
能否支持ctrv v上传图片

### ISSUE THREAD

**Issue by imgwho** [aimerforreimu/auxpi#56]
## Question（提问）

能否支持ctrv v上传图片
类似https://www.superbed.cn/
![image](https://user-images.githubusercontent.com/16558238/57969059-d06e5580-79a4-11e9-87f7-7e56cef76389.png)

**Comment by aimerforreimu** [comment]
@imgwho [https://github.com/aimerforreimu/auxpi/issues/55](https://github.com/aimerforreimu/auxpi/issues/55)
