### ISSUE TITLE
本地图床上传出错

### ISSUE THREAD

**Issue by dudt** [aimerforreimu/auxpi#59]
#### Steps to reproduce（问题复现步骤）

1. [打开网站]
2. [默认本地图床上传]
3. [报错]

#### Screenshot or Gif（截图或动态图）
![Snipaste_2019-05-31_23-30-07](https://user-images.githubusercontent.com/19968269/58717003-d4ff2900-83fc-11e9-9695-d0ce59665181.png)

#### Server environment（服务器环境）
- Your OS & version (服务器系统&版本):BT
- DataBase & version (数据库&版本):

#### Other relevant information（格外信息）
- auxpi version:

**Comment by 0xDkd** [comment]
刷新页面，xsrf token过期了

**Comment by dudt** [comment]
刷新也不行，是不是因为开了CF原因?
