### ISSUE TITLE
部署运行的时候提示错误

### ISSUE THREAD

**Issue by logdns** [aimerforreimu/AUXPI#6]
# 赋予权限
chmod u+x auxpi
# 运行程序
./auxpi
![QQ截图20190219094552.jpg](https://img01.sogoucdn.com/app/a/100520146/9a41f346b81d5b1ca4aba5553eb7d470)

**Comment by aimerforreimu** [comment]
@logdns 
抱歉，不知道什么原因导致 linux 版本中没有二进制程序，现在重新下载程序即可

**Comment by logdns** [comment]
感谢你的帮助,架设成功
测试flickr图床提示这个错误,flickr配置如何填写,我获取到的只有API
![QQ截图20190219113222.jpg](https://i.loli.net/2019/02/19/5c6b794437c0e.jpg)
![QQ截图20190219113222.jpg](https://i.loli.net/2019/02/19/5c6b794437c0e.jpg)

**Comment by logdns** [comment]
![QQ截图20190219113153.jpg](https://i.loli.net/2019/02/19/5c6b7944390a4.jpg)

**Comment by logdns** [comment]
jd的也无法上传

![QQ截图20190219115630.jpg](https://img03.sogoucdn.com/app/a/100520146/6566af5b275613f7813063d73875f8df)

**Comment by aimerforreimu** [comment]
@logdns 

京东图床有最小图片限制，而且这个版本中貌似存在一点问题，下个版本已经修复

flickr 这个图床有工具可以获取其它配置

**Comment by aimerforreimu** [comment]
Flickr 图床对接工具使用方式如下

```bash
wget https://github.com/aimerforreimu/AUXPI/releases/download/1.5.0/flickr.zip

unzip flickr.zip

chmod u+x flickr

./flickr

```
按照提示填写即可

**Comment by logdns** [comment]
您有QQ或者其他联系方式吗?
还是有几个问题,我架设的你看看
1.默认打开上传提示,错误,
![QQ截图20190219142249.jpg](https://ws4.sinaimg.cn/large/5d821655ly1g0bppv2uqpj219c0kdmyo.jpg)
![QQ截图20190219142320.jpg](https://ws4.sinaimg.cn/large/5d821655ly1g0bpq8q569j20o40cu40l.jpg)
配置截图
![QQ截图20190219142516.jpg](https://ws4.sinaimg.cn/large/5d821655ly1g0bprqgdl8j20ff0px0tz.jpg)

**Comment by logdns** [comment]
flickr对接了,可以上传但是图片会无效显示
![QQ截图20190219140810.jpg](https://farm8.staticflickr.com/7906/33267465338_59fd8f76cf_.jpg)

**Comment by aimerforreimu** [comment]
@logdns Flickr 再使用 o 的时候确实会出现无法获取到图片的问题

https://www.flickr.com/services/api/misc.urls.html

当使用 o 等级图片的时候

应该是这样对 url 进行构造

`https://farm{farm-id}.staticflickr.com/{server-id}/{id}_{o-secret}_o.(jpg|gif|png)`

现在拿一个等级为 h 的图片进行举栗子

`https://farm8.staticflickr.com/7818/33271596988_fa03b6a024_h.jpg`

如果要取用 o 等级的话则为

`https://farm8.staticflickr.com/7818/33271596988_o-fa03b6a024_o.jpg`

但是不知道为什么无法获取到原图……很迷

**Comment by logdns** [comment]
如果是用h的等级的话图片是可以获取到的,程序是不是默认使用等级o了, 程序可以默认要求获取h等级吗?
test:
https://farm8.staticflickr.com/7903/32209366467_cab99b1e35_.jpg

https://farm8.staticflickr.com/7903/32209366467_cab99b1e35_h.jpg

还有默认图床上传提示错误不知道是啥情况
![QQ截图20190220091750.jpg](https://ws2.sinaimg.cn/large/005BYqpgly1g0cmi7wwtyj310w0h5js5.jpg)

test 地址 https://imgs.tu.my/

**Comment by aimerforreimu** [comment]
建议下载一下新的程序，然后只需要替换旧程序中的一下auxpi这个文件，然后重启即可

**Comment by logdns** [comment]
新下载程序,默认图床是OK了

Flickr图床还是无法获取到h等级的图片地址,
![QQ截图20190220143201.jpg](https://farm8.staticflickr.com/7855/47101246102_3dd977d372_h.jpg)

您的演示我测试了可以获取到h等级的图
![QQ截图20190220143315.jpg](https://farm8.staticflickr.com/7876/47101250302_9158637d9a_h.jpg)

**Comment by aimerforreimu** [comment]
在后台 json 中Flickr 的那一部分

```json
"flickr_account": {
      "default_size": "",
      "id": "",
      "api_key": "",
      "api_secret": "",
      "oauth_token": "",
      "oauth_token_secret": ""
    }
```
修改 如下
`"default_size": "h"`

**Comment by logdns** [comment]
感谢 成功解决, 程序非常好,期待继续更新完善,

jd那个图床 问题  期待在下个版本解决或者去掉也行

thx

**Comment by aimerforreimu** [comment]
感谢支持
