### ISSUE TITLE
图床分发 改进建议

### ISSUE THREAD

**Issue by keramist** [aimerforreimu/auxpi#63]
本地上传图片分发 
保存文件夹名及文件名和路径 方便查找修改
分发完 后台显示分发的各大图床url
本地图片url固定 利用url跳转实现各大图床自动切换

这样图床就可以使用本地机器管理
frp反代即可实现大存储空间 低费用

**Comment by 0xDkd** [comment]
没弄明白你在说啥，请先搞懂auxpi的分发逻辑
