### ISSUE TITLE
关于图床有没有注意事项？

### ISSUE THREAD

**Issue by lucasjinreal** [aimerforreimu/auxpi#66]
比如，哪个图床容易被封？哪个图床不能快速的连续上传图片？哪个图床可能比较持久？
希望大佬出来讲解一下

**Comment by lucasjinreal** [comment]
以及哪个图床的加载速度最快？

**Comment by 0xDkd** [comment]
@jinfagang 以前委托同学用 Topics 熵权法做过一个排序，但是由于客观数据不足就放弃了，感觉这个东西还是主观排序比较好，我也没有去具体测试过

**Comment by lucasjinreal** [comment]
@aimerforreimu  没有用爬虫去测试吗，比如高频率传图有没有可能被封，这些免费的API里面，总感觉没有免费的午餐，到时候图放上去，结果来一个防止盗链，那就GG了。

目前auxpi里面每一张图片上传是随机上传到某一个图创，还是全部上传并且备份？

**Comment by 0xDkd** [comment]
auxpi 可以自主切换图床的，如果图片防盗链了，是可以自动根据图片找到根节点上面的图片，然后重新上传一张图片到其它的 CDN，一直到回源为止

**Comment by 0xDkd** [comment]
目前的v2 上传是这样的

0.将图片内容以及信息写入内存中
1.拿到内存地址完成上传到根节点（本地，github，gitee，flickr，imgur 等不会发生丢失的图床）的任务，并且生成唯一 hash
2.异步上传到权重排第一的图床上面去（上传之前需要检测图床是否有防盗链等限制措施）
3.释放内存，更新数据库并且写入 Redis 中

当用户访问图片的时候会触发异步检测机制，如果图片挂了，那就重复上面的2-3 步。

当然为了性能考虑只有在 Redis 缓存未命中的时候才回去检测是否防盗链，所以性能问题不用太担心
