### ISSUE TITLE
大佬QQ图床那个很稳定,希望添加

### ISSUE THREAD

**Issue by cjiasu** [aimerforreimu/auxpi#67]
https://puui.qpic.cn/fans_admin/0/3_526421126_1559738139791/0

图片地址是这样的 好像腾讯视频的  希望加入  目前 百度 360 阿里都有了就差腾讯了

**Comment by 0xDkd** [comment]
需要使用cookie鉴权，后期可以考虑，暂时不考虑需要cookie鉴权的图床

**Comment by dyan33** [comment]
> 需要使用cookie鉴权，后期可以考虑，暂时不考虑需要cookie鉴权的图床



> https://puui.qpic.cn/fans_admin/0/3_526421126_1559738139791/0
> 
> 图片地址是这样的 好像腾讯视频的 希望加入 目前 百度 360 阿里都有了就差腾讯了

请问这个图片地址在哪里获取的
