### ISSUE TITLE
How does a struct can call UnmarshalJSON this method

### ISSUE THREAD

**Issue by lucasjinreal** [aimerforreimu/auxpi#69]
```
data := tools.AliFormPost(file, url)
	j := AliResp{}
	j.UnmarshalJSON([]byte(data))
```

`AliResp` is a struct, how does it call `j.UnmarshalJSON` method?

**Comment by 0xDkd** [comment]
EasyJson can do this,u can see code in  [here](https://github.com/aimerforreimu/auxpi/blob/e0903e24813ffebe73aadac3d80b2ea20006ce39/auxpiAll/all.go#L294)

EasyJson repo [https://github.com/mailru/easyjson](https://github.com/mailru/easyjson)
