### ISSUE TITLE
设置默认的图床不生效，

### ISSUE THREAD

**Issue by mutouxia** [aimerforreimu/AUXPI#7]
siteConfig.json修改了默认图床Sina， 重启，首页还是yahoo图标，也上传不成功，手工点左侧新浪图床可以上传，
![Snipaste_2019-02-19_19-15-38.png](https://ws3.sinaimg.cn/large/007DFgJwly1g0byc1g3dej30dt0b0h6q.jpg)
![Snipaste_2019-02-19_19-15-58.png](https://ws3.sinaimg.cn/large/007DFgJwly1g0byc17j6hj30e30fx4qp.jpg)
![Snipaste_2019-02-19_19-16-16.png](https://ws1.sinaimg.cn/large/007DFgJwly1g0byc22we8j30wy0i1x6q.jpg)
![Snipaste_2019-02-19_19-16-36.png](https://ws1.sinaimg.cn/large/007DFgJwly1g0byc2nu6xj30vl0lue83.jpg)

**Comment by aimerforreimu** [comment]
@mutouxia 收到，下个版本修复

**Comment by aimerforreimu** [comment]
目前后台已经写的差不多了，估计下个版本不需要操作去修改 json，并且这个紫色的图标其实是本地图床的可能我编译的时候用错仓库了

**Comment by aimerforreimu** [comment]
@mutouxia 

目前只下载新的程序，直接使用现在最新的程序即可 或者 替换掉 auxpi 这个二进制文件，就可以去除本地图床，不过默认图床的 bug 仍旧没有修改

**Comment by mutouxia** [comment]
好的，，谢谢！

**Comment by aimerforreimu** [comment]
fix [#7](https://github.com/aimerforreimu/AUXPI/commit/00e061273b6a74e0c85ed7feb744fc58d0e2c797)
