### ISSUE TITLE
如何在代码中调用？

### ISSUE THREAD

**Issue by lucasjinreal** [aimerforreimu/auxpi#70]
想通过读取本地文件，直接调用某个接口上传。

```
imgBytes, _ := ioutil.ReadFile(imgFilePath)

		imgParam := auxpi.ImageParam{
			Name:    imgFilePath,
			Type: "jpg",
			Content: &imgBytes,
		}

		client := auxpi.Ali{FileLimit: nil, MaxSize: 5024}
		res, err := client.Upload(&imgParam)
		fmt.Println(res)
		if err != nil {
			fmt.Println(err)
		}
```

结果拿不到返回的url：

```
{"code":"2"}

```

这个code是啥意思

**Comment by 0xDkd** [comment]
```go
.
.
.
import "github.com/auxpi/server"
.
.
.
//传入值可以看这里  https://github.com/aimerforreimu/auxpi/wiki/API-%E4%B8%8A%E4%BC%A0#%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0-v1-%E6%8E%A5%E5%8F%A3
client := server.NewClient("ali")
if client.Error != nil {
		//error handle
	}
content, _ := ioutil.ReadFile(imgFilePath)
//构造传入参数
	image := server.ImageParam{
		Name:    h.Filename,
		Type:    h.Header.Get("Content-Type"),
		Info:    h.Header.Get("Content-Disposition"),
		Content: &content,
	}
	client.Do(&image)
fmt.Println(client.Resp)
```

具体的实现是使用 interface 实现的，将所有 server 都必须有一个 [Uploader](https://github.com/aimerforreimu/auxpi/blob/e0903e24813ffebe73aadac3d80b2ea20006ce39/server/index.go#L21) ,实例化一个 `Manager` 的 struct，将实现了 `Uploader` 接口的 `Client` 注册到 `Manger` 的列表中，这样就可以直接使用 `client := server.NewClient("ali")` 来实例化一个 `Uploader`的 `Clinet`，然后就可以进行上传操作了

**Comment by lucasjinreal** [comment]
@aimerforreimu  多谢回答。
这里面的这个h是啥子？？

另外我直接构造一个ImageParam参数，直接实例化Ali这个client，为啥传不上去？具体来讲这个ImageParam参数可能构造不正确？

**Comment by 0xDkd** [comment]
h 的类型为 `*multipart.FileHeader` 

```
image := server.ImageParam{
		Name:    "FileName",
		Type:    "File Mime Type",
		Info:    "File desc",
		Content: &content, //byte pointer
	}
```

我感觉错误可能出在你的 content 上面，content 是 `[]byte` 类型的指针，你可以打印一下 content 的值，看看是否为空

**Comment by lucasjinreal** [comment]
@aimerforreimu  Got it.

目前能不能从代码做到这么一点：

> 指定若干图床，比如不用登陆的， 国内的，没有防盗链的，然后通过一个统一化的接口，根据图床得分选择一个上传返回url。

这样可以降低单个图床一死死一片的概率。这个在代码当中应该如何调用？

**Comment by 0xDkd** [comment]
@jinfagang 目前是可以做到的，请看这段代码
[https://github.com/aimerforreimu/auxpi/blob/e0903e24813ffebe73aadac3d80b2ea20006ce39/server/index.go#L148](https://github.com/aimerforreimu/auxpi/blob/e0903e24813ffebe73aadac3d80b2ea20006ce39/server/index.go#L148)

实例化好以后可以根据排名进行上传，不过排名要自己选。

至于你说的的这个需求我感觉有点问题

如果你的图片已经上传到了第三方的 OOS\CDN 上面,就必须得接受可能被删除或者 CDN 出现防盗链的问题。如果想要从根本上解决这个问题，可以考虑使用一个跳转链接，就是我前面提到的 [https://github.com/aimerforreimu/auxpi/issues/66#issuecomment-507984951](https://github.com/aimerforreimu/auxpi/issues/66#issuecomment-507984951) 这个解决方法。目前 AUXPI 是支持这种分发上传的。

另外如果要追求无 302 跳转的话还有一种方法，使用编辑器预处理+后台程序处理，在插入图片的时候使用这种形式

```
<img  alt="0" src="https://ae01.alicdn.com/kf/UTB8G0.jP4HEXKJk43Je761eeXXao.png" data-root="https://test.demo-1s.com/dispatch/625b4b0c2d6c36b991131647c9b92d2e" />
```

这样在就不需要 302 跳转，可以直接访问第三方的 CDN，如果图片挂掉的话,只需要让后台特定的程序去请求 data-root 的值，获得到最新的CDN 链接替换 src 中的值就可以了。这么处理要增大不少程序量和逻辑，但是这么处理是我能想出来最好方法了。

**Comment by lucasjinreal** [comment]
@aimerforreimu  
```
NewClientOrderBySpeed
```
这个方法能不能指定某些图床？因为有些图床可以直接pass掉，比如新浪的要登录和防盗链的，国外的低速的，以及可能不具备本地图床。

**Comment by 0xDkd** [comment]
可以的，排名可以按照自己的想法写，我只是提供了我认为快的一些图床

**Comment by lucasjinreal** [comment]
主要是，
