### ISSUE TITLE
通过 Auxpi-Admin 登陆无效

### ISSUE THREAD

**Issue by flashjay** [aimerforreimu/auxpi#73]
## Bug report（问题描述）
访问 /admin 使用邮箱/用户名登陆都无效
#### Steps to reproduce（问题复现步骤）

1. Auxpi-Admin /admin#/login?redirect=%2Fdashboard登陆无法使用
  不管使用管理员邮箱或者用户名都提示 “请输入正确的用户名”

#### Server environment（服务器环境）
- Your OS & version (服务器系统&版本):
macos
- DataBase & version (数据库&版本):
mysql

#### Other relevant information（格外信息）
- auxpi version:dev

**Comment by 0xDkd** [comment]
请确保用户名长度大于 6，否则前端验证通过不了

**Comment by flashjay** [comment]
这个项目的前端缺少一些构建文件（可能是我不熟悉）
我想修改成支持6个字符以内长度，改完发现重新构建失败。
@see #72

**Comment by 0xDkd** [comment]
yarn install 了吗

**Comment by flashjay** [comment]
@aimerforreimu 
yarn install 做了，应该是 .gitignore 忽略了 build/ 导致 resource里面的 build目录也被忽略了，你没有提交这个目录；
.gitignore  应该设置忽略 /build，不要把   resource 目录下的 build也忽略掉。

**Comment by flashjay** [comment]
我用vue2.x新建了个demo，把build目录拷过去用，并修改了 svg 的支持，现在可以了，但是你这个源码提交的不完整；还是谢谢哈。

**Comment by xihefeng** [comment]
> 我用vue2.x新建了个demo，把build目录拷过去用，并修改了 svg 的支持，现在可以了，但是你这个源码提交的不完整；还是谢谢哈。

请问是否方便提供下这份build文件？十分感谢~
