### ISSUE TITLE
发现安装程序是需要安装Redis的

### ISSUE THREAD

**Issue by luckskypig** [aimerforreimu/auxpi#74]
安装过程中使用了宝塔面板安装，wiki里面好像只提到了安装mysql和nginx。然后我安装的时候提示连接到6379端口失败。后面安装上Redis后发现就可以初始化安装运行了。
使用宝塔面板安装的时候大家可以注意下Redis是否已经安装。
最后感谢作者~

**Comment by 0xDkd** [comment]
可以通过修改 app.conf 中的配置进行缓存配置的修改
