### ISSUE TITLE
本地图床返回的 URL 无法插入数据库

### ISSUE THREAD

**Issue by capric98** [aimerforreimu/auxpi#75]
```
[A] [asm_amd64.s:1333]  本地图床返回的 URL 无法插入数据库, URL为:http://176.96.138.79:2333/images/2019/07/21/o7mIr1wE2zlCd3eM.jpg
```
使用一键脚本安装图床程序（不包含nginx,mysql等），cache使用memory；
./auxpi init后添加管理员auxpi@0w0.tn 123123123，后台更改站点链接为http://176.96.138.79:2333
（目前demo运行中）
后上传图片正常，但log中显示无法插入数据库，在后台也看不到上传的图片，但是通过链接可以访问图片
LOG见http://176.96.138.79/log.txt

**Comment by 0xDkd** [comment]
数据库连接上了吗

**Comment by capric98** [comment]
应该连上了？未更改站点地址的时候似乎是正常的。。
稍后我再检查下OTZ

**Comment by lllbbbyyy** [comment]
请问这个问题是如何解决的呢，我也遇到了相同的问题

**Comment by lllbbbyyy** [comment]
> 请问这个问题是如何解决的呢，我也遇到了相同的问题

没事了，看了一下源码发现是对于网址格式的正则表达式匹配检查不支持，通过直接修改源码自行编译的方式解决了
