### ISSUE TITLE
执行 ./auxpi migrate`./auxpi init时出错

### ISSUE THREAD

**Issue by xss9626** [aimerforreimu/auxpi#76]
## Question（提问）

执行auxpi init 显示
[root@iz2zec9sx8vfuzeq5rhts3z auxpi]# ./auxpi migrate
panic: dial tcp 127.0.0.1:6379: connect: connection refused
执行./auxpi migrate显示
goroutine 1 [running]:
github.com/auxpi/bootstrap.initCache(0xc00000a420, 0xc000047f30)
	/Users/aimer/go/src/github.com/auxpi/bootstrap/Config.go:220 +0x71a
 panic: dial tcp 127.0.0.1:6379: connect: connection refused

**Comment by 0xDkd** [comment]
如果没有redis的话请把cache关掉或者使用其他驱动，具体看app. ini的配置

**Comment by xss9626** [comment]
用2.3.6安装然后用最新版覆盖ª成功运行

**Comment by xss9626** [comment]
问题解决了谢谢大佬
