### ISSUE TITLE
在./auxpi migrate过程中出现错误

### ISSUE THREAD

**Issue by ClementineZou** [aimerforreimu/auxpi#77]
我通过文档中的自动脚本进行安装，但在执行./auxpi migrate命令时出现错误，如下，我应该如何更正它？谢谢

[root@VM_189_195_centos auxpi]# ./auxpi migrate
2019/07/29 17:00:26 [info] replacing callback `gorm:update_time_stamp` from /Users/aimer/go/src/github.com/auxpi/models/models.go:80
2019/07/29 17:00:26 [info] replacing callback `gorm:update_time_stamp` from /Users/aimer/go/src/github.com/auxpi/models/models.go:81
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b8 pc=0x9a69b9]

goroutine 1 [running]:
github.com/auxpi/utils.init()
	/Users/aimer/go/src/github.com/auxpi/utils/jwt.go:24 +0xd9

**Comment by 0xDkd** [comment]
建议使用最新版程序
