### ISSUE TITLE
再次部署，提示出错

### ISSUE THREAD

**Issue by taraway** [aimerforreimu/auxpi#8]
一次部署完运行是正常的，修改了基础配置，kill进程，重新运行，提示这个，啥情况呀，第一次接触go语言~
<img src="https://img01.sogoucdn.com/app/a/100520146/03d8562aa87d1db1fac343d829033ba1" alt="1.png" title="1.png" />

**Comment by vast0906** [comment]
@taraway    方便透露下怎么解决的吗

**Comment by taraway** [comment]
@vast0906  程序访问路径，我自己弄错了~
