### ISSUE TITLE
./auxpi init 过程出现connect: connection refused

### ISSUE THREAD

**Issue by huangwb8** [aimerforreimu/auxpi#83]
## Bug report（问题描述）
我使用的版本是auxpi-2.3.9-linux.tar.gz. 
当下载下来后，在根目录下执行./auxpi init时，出现报错：
panic: dial tcp 127.0.1.1:6379: connect: connection refused

goroutine 1 [running]:
github.com/auxpi/bootstrap.initCache(0xc0000f83c0, 0xc0000e1f30)
	/Users/aimer/go/src/github.com/auxpi/bootstrap/Config.go:220 +0x71a
#### Steps to reproduce（问题复现步骤）
```shell
wget https://github.com/aimerforreimu/auxpi/releases/download/2.3.9/auxpi-2.3.9-linux.tar.gz
tar -zxvf auxpi-2.3.9-linux.tar.gz 
# 复制/build/linux目录下的文件到当前目录
sudo chmod -u+x auxpi
./auxpi init
```
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/35643122/64792383-eb944f00-d5ab-11e9-9475-0ff8bc2612ff.png)

#### Server environment（服务器环境）
- Your OS & version (服务器系统&版本): Ubuntu 18.04.3 LTS
- DataBase & version (数据库&版本):MySQL 5.5.62

**Comment by huangwb8** [comment]
已解决，我使用了旧的版本：auxpi-2.3.6-linux.tar.gz，即没有类似问题。

**Comment by 0xDkd** [comment]
可以不用redis做缓存
或者安装redis

具体如何修改，请看app. conf
