### ISSUE TITLE
api请求出现400

### ISSUE THREAD

**Issue by moonrailgun** [aimerforreimu/auxpi#86]
## Question（提问）

![TIM截图20190923210502](https://user-images.githubusercontent.com/6964737/65427924-fbcaea80-de45-11e9-86d5-e65e34807e5d.png)

看了下代码没有找出问题

后台不论选择什么apiSelect都打印:
![TIM截图20190923210418](https://user-images.githubusercontent.com/6964737/65427945-05545280-de46-11e9-8908-3a40b58f1d93.png)

在网页端可以正常上传

**Comment by 0xDkd** [comment]
400为认证失败
请按照wiki进行操作，认证是在Header做的认证

**Comment by moonrailgun** [comment]
我这边是按照README的说明来构造请求的，看上去readme的文档已经过时
希望能更新readme或增加到wiki的连接。

**Comment by 0xDkd** [comment]
好的，收到
