### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by swordstudiox** [aimerforreimu/AUXPI#9]
1、运行一段时间后页面就报HTTP ERROR 500错误了
2、运行成功了就出现这个
Handler crashed with error can't find templatefile in the path:views/webUpload/box.tpl[0m
2019/02/24 11:56:48.293 [1;35m[C] [asm_amd64.s:522]  /usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:522[0m
2019/02/24 11:56:48.293 [1;35m[C] [asm_amd64.s:522]  /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513[0m
2019/02/24 11:56:48.293 [1;35m[C] [asm_amd64.s:522]  /Users/aimer/go/src/github.com/astaxie/beego/template.go:73[0m

3、怎么重启软件都不行，只能重启服务器

**Comment by aimerforreimu** [comment]
根据提示来看是找不到模板文件，你是否删除过 views 目录下的文件？
