### ISSUE TITLE
安装后，初始化显示github.com/auxpi/bootstrap.initCache(0xc00000a440, 0xc00004bf30)         /Users/aimer/go/src/github.com/auxpi/bootstrap/Config.go:220 +0x71a

### ISSUE THREAD

**Issue by vim0x22** [aimerforreimu/auxpi#99]
应该安装后，执行初始化命令出现此错误，有遇到过类似情况的吗
github.com/auxpi/bootstrap.initCache(0xc00000a440, 0xc00004bf30)
        /Users/aimer/go/src/github.com/auxpi/bootstrap/Config.go:220 +0x71a

**Comment by waleraye** [comment]
你好,这个是怎么处理的呀
